# export.py
# PhishGuard - Report Export System
# Exports scan results to TXT or CSV format

import csv
import os
from datetime import datetime

# Default output directory
REPORTS_DIR = "reports"


def ensure_reports_dir():
    """Creates the reports directory if it doesn't exist."""
    if not os.path.exists(REPORTS_DIR):
        os.makedirs(REPORTS_DIR)


def export_txt(result: dict, email_preview: str = "") -> str:
    """
    Exports scan result as a formatted TXT report.
    Returns the file path of the saved report.
    """
    ensure_reports_dir()

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = os.path.join(REPORTS_DIR, f"phishguard_report_{timestamp}.txt")

    try:
        with open(filename, "w", encoding="utf-8") as f:
            f.write("=" * 50 + "\n")
            f.write("         PhishGuard - Scan Report\n")
            f.write("=" * 50 + "\n\n")

            f.write(f"Date / Time  : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Risk Level   : {result.get('risk_level', 'N/A')}\n")
            f.write(f"Risk Score   : {result.get('score', 0)} / {result.get('max_score', 10)}\n\n")

            f.write("DETECTED ISSUES:\n")
            f.write("-" * 30 + "\n")
            for detail in result.get("details", []):
                f.write(f"  {detail}\n")

            if not result.get("details"):
                f.write("  No issues detected.\n")

            f.write("\n")
            f.write("SUGGESTED ACTION:\n")
            f.write("-" * 30 + "\n")
            f.write(f"  {result.get('suggested_action', 'N/A')}\n\n")

            if email_preview:
                f.write("EMAIL PREVIEW:\n")
                f.write("-" * 30 + "\n")
                f.write(f"  {email_preview[:200]}...\n\n")

            f.write("=" * 50 + "\n")
            f.write("       Generated by PhishGuard V5\n")
            f.write("=" * 50 + "\n")

        return filename

    except Exception as e:
        print(f"[Export] TXT export failed: {e}")
        return ""


def export_csv(history: list) -> str:
    """
    Exports the full scan history as a CSV report.
    Returns the file path of the saved report.
    """
    ensure_reports_dir()

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = os.path.join(REPORTS_DIR, f"phishguard_history_{timestamp}.csv")

    try:
        with open(filename, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)

            # Header row
            writer.writerow(["Session", "Time", "Risk Level", "Score", "Flags", "Email Preview"])

            # Data rows
            for entry in history:
                writer.writerow([
                    entry.get("session", ""),
                    entry.get("time", ""),
                    entry.get("risk", ""),
                    entry.get("score", ""),
                    entry.get("flags", ""),
                    entry.get("preview", "")
                ])

        return filename

    except Exception as e:
        print(f"[Export] CSV export failed: {e}")
        return ""